# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d89d35cab672a345154b1a5d9c12fd1b5e055c487ec6c9b801ce909391bb008edb424ebb8803a6a7aa8fcfa6356b7e7f42aca370d8841850c9d4abedc4cbfaec

test:
  secret_key_base: 1ff8e0bcf5f4dbdf3700131fbf3cbd9d6ffe77509207620745e4f35b23bedef934a028e9c59f4ab2365368032e04338474428f77188037735aeea289c075751d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
